<a href="https://colab.research.google.com/github/husthorng/GA/blob/main/1_Backpropagation_T1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

In [ ]:
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])

y = np.array([[0],
            [1],
            [1],
            [0]])

In [ ]:
X=np.insert(X,X[0].size,1,axis=1)

In [ ]:
np.random.seed(1)


In [ ]:

# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((X[0].size,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1



In [ ]:
syn1

array([[-0.1653904 ],
       [ 0.11737966],
       [-0.71922612],
       [-0.60379702]])

In [ ]:
for j in range(60000):

	# Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2

    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))

    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)

    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)


Error:0.49824033388986244
Error:0.011392213915157014
Error:0.007828508943529568
Error:0.0063146154235726
Error:0.005428922859423809
Error:0.004831273284359524


In [ ]:
X[0]

array([0, 0, 1, 1])

In [ ]:
#print output
print("output after Training:")
print(l2)

output after Training:
[[0.004011  ]
 [0.99645285]
 [0.9952215 ]
 [0.00523755]]


In [ ]:
X = np.array([[1,1,0],[1,0,1]])
l0 = np.insert(X,X[0].size,1,axis=1)
l1 = nonlin(np.dot(l0,syn0))
l2 = nonlin(np.dot(l1,syn1))
#print output
print("output after Training:")
print(l2)

output after Training:
[[0.00516171]
 [0.99522154]]
